services:
  neo4j:
    image: neo4j:4.3
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - neo4j

volumes:
  neo4j_data: